version: '3'

services:
    
    database:
        container_name: "postgres-db"
        image: "postgres"
        environment:
          - POSTGRES_USER=testuser
          - POSTGRES_PASSWORD=testpass
          - POSTGRES_DB=file_storage
        ports:
            - "5432:5432"

    redis:
        container_name: "redis-db"
        image: redis:latest
        ports:
            - "6379:6379"

    web:
        build: .
        privileged: true
        ports:
         - "8080:8080"
        depends_on:
            - database
            - redis